version: '2'
services:
    demosinwebsockets-app:
        image: demosinwebsockets
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://demosinwebsockets-mysql:3306/demosinwebsockets?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demosinwebsockets-mysql:
        extends:
            file: mysql.yml
            service: demosinwebsockets-mysql
